<?php

require_once("lib/VyewAPI.php");

// http://vyew.com/api/public/ -- click "Get API Key"
/*
Key: 64bc5dcf29
Secret: 5cef774a5d685f53b3ef 
*/


function _vyew() {
  static $vyew;

  if (! (is_object($vyew))) {
    $api_key = "d43a9866b5";
    $api_secret = "f2ea525865ce6cfb7f99";
    $vyew = new VyewAPI($api_key, $api_secret);
  }
  return $vyew;
}

/*
 * Implementation of hook_menu()
 */

function vyew_menu() {
  $items['vyew'] = array (
			  'title' => 'Vyew test',
			  'page callback' => 'vyew_test',
			  'access arguments' => array('administer nodes'),
			  'type' => MENU_CALLBACK,
			  );
  $items['users/%/room/edit'] = array (
					 'title' => 'Configure Vyew Room',
					 'page callback' => 'vyew_edit_user_room',
					 'file' => 'room.edit.inc',
					 'page arguments' => array(1),
					 'access arguments' => array ('administer users'),
					 );
  $items['users/%/room'] = array (
				       'title callback' => 'vyew_room_title_callback',
				       'title arguments' => array(1),
				       'page callback' => 'vyew_room',
				       'page arguments' => array(1),
				       'file' => 'vyew.pages.inc',
				       'access arguments' => array ('access content')
				       );
				       
  return $items;
}

function vyew_room_title_callback($uid) {
  $u = user_load($uid);
  if ($u) {
    $name = $u->name;
  } else {
    $u = user_load(array('name' => $uid));
    if ($u) {
      $name = $u->name;
    } else {
      return "Page not found";
    }
  }
  $room = vyew_room_settings_load($u->uid);
  return ($room->room_title ? $room->room_title : 'My Room');
}

function vyew_room_settings_load($uid) {
  $result = db_query("SELECT * FROM {eto_vyew_room} WHERE uid = %d",
		     $uid);
  return db_fetch_object($result);
}




function vyew_test() {
  $output = "";

  $vyew = _vyew();

  $res=$vyew->create('Test Meeting');

  $output .= "Hi<P>";
  print_r2($res);
  return $output;
  

}

/*
 * Takes a student ID, returns the room for them
 */

function get_student_room($student_id) {
  if (!$student_id) { return ""; }

  

}