<?php

/*
 * Implementation of hook_menu()
 */

function vyew_menu() {
  $items['vyew'] = array (
			  'title' => 'Vyew test',
			  'page callback' => 'vyew_test',
			  'access arguments' => array('administer nodes'),
			  'type' => MENU_CALLBACK,
			  );
  $items['users/%/room/edit'] = array (
					 'title' => 'Configure Vyew Room',
					 'page callback' => 'vyew_edit_user_room',
					 'file' => 'room.edit.inc',
					 'page arguments' => array(1),
					 'access arguments' => array ('administer users'),
					 );
  $items['users/%/room'] = array (
				       'title callback' => 'vyew_room_title_callback',
				       'title arguments' => array(1),
				       'page callback' => 'vyew_room',
				       'page arguments' => array(1),
				       'file' => 'vyew.pages.inc',
				       'access arguments' => array ('access content')
				       );
  $items['users/%/room/%'] = array (
				       'title callback' => 'vyew_room_title_callback',
				       'title arguments' => array(1),
				       'page callback' => 'vyew_room',
				       'page arguments' => array(1, 3),
				       'file' => 'vyew.pages.inc',
				       'access arguments' => array ('access content')
				       );
				       
  return $items;
}

/*
 * Implementation of hook_perm()
 */

function vyew_perm() {
  return array(
	       'edit own vyew room settings',
	       'edit any vyew room settings',
	       );
}


function vyew_room_title_callback($uid) {
  $u = eto_user_load($uid);
  if ($u) {
    $name = $u->name;
  } else {
    $u = eto_user_load(array('name' => $uid));
    if ($u) {
      $name = $u->name;
    } else {
      return "Page not found";
    }
  }
  $room = vyew_room_settings_load($u->uid);
  return ($room->room_title ? $room->room_title : 'My Room');
}

function vyew_room_settings_load($uid) {
  $result = db_query("SELECT * FROM {eto_vyew_room} WHERE uid = %d",
		     $uid);
  return db_fetch_object($result);
}




function vyew_test() {
  $output = "";

  $vyew = _vyew();

  $res=$vyew->create('Test Meeting');

  $output .= "Hi<P>";
  print_r2($res);
  return $output;
  

}

/*
 * Takes a student ID, returns the room for them
 */

function get_student_room($student_id) {
  if (!$student_id) { return ""; }

  

}