<?php

/**
 * Implementation of hook_menu()
 */

function student_menu() {

  /**********************************************************************
   **********************************************************************
   **
   ** Application stuff
   **
   **********************************************************************
   **********************************************************************/


  $items['user/student/application'] = array (
					    'title' => 'Student Application',
					    'page callback' => 'student_application',
					    'access arguments' => array('access content'),
					    'file' => 'application.inc',
					    'type' => MENU_NORMAL_ITEM,
					    );
  $items['users/%/student/application'] = array (
					      'title callback' => 'title_callback_student_application',
					      'title arguments' => array(1),
					      'page callback' => 'student_application',
					      'page arguments' => array(1),
					      'access arguments' => array('access content'),
					      'file' => 'application.inc',
					      'type' => MENU_NORMAL_ITEM,
					      );
  $items['user/student/application/profile'] = array (
						'title' => 'Student Application: Biographical Information',
						'page callback' => 'student_application_profile',
						'access arguments' => array('access content'),
						'file' => 'application.inc',
						'type' => MENU_CALLBACK,
						);
  $items['users/%/student/application/profile'] = array (
						  'title callback' => 'title_callback_student_application',
						  'title arguments' => array(1, "Biographical Information"),
						  'page callback' => 'student_application_profile',
						  'page arguments' => array(1),
						  'access arguments' => array('access content'),
						  'file' => 'application.inc',
						  'type' => MENU_CALLBACK,
						  );
  $items['user/student/application/consent'] = array (
						    'title' => 'Student Application: Consent and Payment',
						    'page callback' => 'student_application_consent',
						    'access arguments' => array('access content'),
						    'file' => 'application.inc',
						    'type' => MENU_CALLBACK,
						    );
  $items['users/%/student/application/consent'] = array (
						      'title callback' => 'title_callback_student_application',
						      'title arguments' => array(1, "Consent and Payment"),
						      'page callback' => 'student_application_consent',
						      'page arguments' => array(1),
						      'access arguments' => array('access content'),
						      'file' => 'application.inc',
						      'type' => MENU_CALLBACK,
						      );
  $items['user/student/application/contact'] = array (
						    'title' => 'Student Application: Contact Information',
						    'page callback' => 'student_application_contact',
						    'access arguments' => array('access content'),
						    'file' => 'application.inc',
						    'type' => MENU_CALLBACK,
						    );
  $items['users/%/student/application/contact'] = array (
						      'title callback' => 'title_callback_student_application',
						      'title arguments' => array(1, "Contact Information"),
						      'page callback' => 'student_application_contact',
						      'page arguments' => array(1),
						      'access arguments' => array('access content'),
						      'file' => 'application.inc',
						      'type' => MENU_CALLBACK,
						      );

  return $items;
}


function title_callback_student_application($uid, $additional = "") {

  $u = user_load($uid);
  if ($u) {
    $name = $u->name;
  } else {
    $u = user_load(array('name' => $uid));
    if ($u) {
      $name = $u->name;
    } else {
      return "Page not found";
    }
  }
  return "Student Application for " . $name . ($additional ? ": $additional" : "");
}

/**
 * Implementation of hook_perm()
 */

function student_perm() {
  return array(
	       'edit own student profile',
	       'edit all student profiles',
	       'administer students',
	       );
}

